# -*- coding: utf-8 -*-
"""Day 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrcFvZrOasKhOX5e-kXW-901ZfbQLgMs
"""

import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(2,3)

print(new_arr)

import numpy as np

marks = np.array([70,80,90,60])

average  = np.mean(marks)

print(average)

import numpy as np

salary = np.array([10000,20000,30000,40000,50000])

med = np.median(salary)

print(med)

"""DAY - 4 : TASK"""

import numpy as np

scores = [58,78,96,34,80]

total = sum(scores)
average = total/len(scores)
highest = max(scores)
lowest = min(scores)

print("student  scores:",scores)
print("Total Marks:",total)
print("Average Marks:",average)
print("Highest Marks:",highest)
print("Highest Marks:",lowest)

import numpy as np

sales = [530000,70000,60000,92000,49000]

total_sales = sum(sales)
average_sales = total_sales/len(sales)
highest_sales = max(sales)
lowest_sales = min(sales)

print("Total Sales:",total_sales)
print("Average sales:",average_sales)
print("Highest sales:",highest_sales)
print("Lowest Sales:",lowest_sales)